# Generated by Django 4.2 on 2023-04-09 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_revenue', models.BooleanField(choices=[(True, 'Revenue'), (False, 'Expenses')])),
                ('revenue_type', models.CharField(blank=True, choices=[('Savings', 'Savings'), ('Salary', 'Salary'), ('Bonuses', 'Bonuses'), ('Interests', 'Interests'), ('Other', 'Other')], max_length=32, null=True)),
                ('expenses_type', models.CharField(blank=True, choices=[('Foods', 'Foods'), ('Gifts', 'Gifts'), ('Medical', 'Medical'), ('Expenses', 'Expenses'), ('Home', 'Home'), ('Transportation', 'Transportation'), ('Personal expenses', 'Personal expenses'), ('Pets', 'Pets'), ('bills', 'bills'), ('Trips', 'Trips'), ('Debts', 'Debts'), ('Other', 'Other'), ('Services', 'Services')], max_length=32, null=True)),
                ('description', models.CharField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Recurring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_revenue', models.BooleanField(choices=[(True, 'Revenue'), (False, 'Expenses')])),
                ('revenue_type', models.CharField(blank=True, choices=[('Savings', 'Savings'), ('Salary', 'Salary'), ('Bonuses', 'Bonuses'), ('Interests', 'Interests'), ('Other', 'Other')], max_length=32, null=True)),
                ('expenses_type', models.CharField(blank=True, choices=[('Foods', 'Foods'), ('Gifts', 'Gifts'), ('Medical', 'Medical'), ('Expenses', 'Expenses'), ('Home', 'Home'), ('Transportation', 'Transportation'), ('Personal expenses', 'Personal expenses'), ('Pets', 'Pets'), ('bills', 'bills'), ('Trips', 'Trips'), ('Debts', 'Debts'), ('Other', 'Other'), ('Services', 'Services')], max_length=32, null=True)),
                ('description', models.CharField(blank=True, null=True)),
                ('until', models.DateField()),
                ('repeat', models.CharField(blank=True, choices=[('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Annually', 'Annually')], max_length=16, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
