# Generated by Django 4.2 on 2023-04-09 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_recurring_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurring',
            name='repeat',
            field=models.CharField(choices=[('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Annually', 'Annually')], max_length=16),
        ),
    ]
