# Generated by Django 4.2 on 2023-04-09 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_recurring_repeat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurring',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'Active'), (False, 'Not Active')]),
        ),
    ]
