# Generated by Django 4.2 on 2023-04-09 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_recurring_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurring',
            name='description',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
