# Generated by Django 4.2 on 2023-06-04 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_alter_recurring_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurring',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='recurring',
            name='expenses_type',
        ),
        migrations.RemoveField(
            model_name='recurring',
            name='is_revenue',
        ),
        migrations.RemoveField(
            model_name='recurring',
            name='revenue_type',
        ),
        migrations.RemoveField(
            model_name='recurring',
            name='user',
        ),
        migrations.AddField(
            model_name='recurring',
            name='transaction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='transactions.transaction'),
            preserve_default=False,
        ),
    ]
